config/routes.rb
Rails.application.routes.draw do
  root to: "customers#index"
  resources :customers do
    member do
      get "versions", to: "customers#versions"
      get "version/:version_id", to: "customers#version", as: "version"
      post "revert/:version_id", to: "customers#revert", as: "revert"
      post "restore", to: "customers#restore", as: "restore"
    end
    collection do
      get "deleted", to: "customers#deleted"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_paper_trail

  validates :first_name, :last_name, :birthday, :country, presence: true
  validate :birthday_date, on: %i[create update], if: :birthday

  private
  def birthday_date
    errors.add(:birthday, ' must be an earlier date.') if birthday > Time.now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[ show edit update destroy versions]
  before_action :set_version, only: %i[version revert]

  # GET /customers or /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1 or /customers/1.json
  def show; end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit; end

  # POST /customers or /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to customer_url(@customer), notice: "Customer was successfully created." }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1 or /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to customer_url(@customer), notice: "Customer was successfully updated." }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1 or /customers/1.json
  def destroy
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url, notice: "Customer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # GET /customers/:id/versions
  def versions
    @customers = @customer.versions
  end

  # GET /customers/:id/versions/:id
  def version; end

  # POST /customers/:id/revert/:version_id
  def revert
    @reverted_customer = @version.reify
    if @reverted_customer.save
      redirect_to versions_customer_path(@version.item_id), notice: "Customer was successfully reverted."
    else
      render version
    end
  end

  # GET /customers/deleted
  def deleted
    @destroyed_versions = PaperTrail::Version.where(item_type: "Customer", event: "destroy").order(created_at: :desc)
    @latest_destroyed_versions = @destroyed_versions.filter { |v| v.reify.versions.last.event == "destroy" }.map(&:reify).uniq(&:id)
    @customers = @latest_destroyed_versions
  end

  # POST /customers/:id/restore
  def restore
    @latest_version = Customer.new(id: params[:id]).versions.last
    if @latest_version.event == "destroy"
      @customer = @latest_version.reify
      if @customer.save
        redirect_to @customer, notice: "Customer was successfully restored."
      else
        render "deleted"
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    def set_version
      @version = PaperTrail::Version.find_by(item_id: params[:id], id: params[:version_id])
    end

    def customer_params
      params.require(:customer).permit(:first_name, :last_name, :birthday, :country)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer.html.erb
<% unless customer.try(:event) && (customer.event == "create" || customer.event == "destroy") %>
    <tr>
      <td class="align-middle text-center"><%= customer.try(:reify) ? customer.reify.first_name : customer.first_name %></td>
      <td class="align-middle text-center"><%= customer.try(:reify) ? customer.reify.last_name : customer.last_name %></td>
      <td class="align-middle text-center"><%= customer.try(:reify) ? customer.reify.birthday : customer.birthday %></td>
      <td class="align-middle text-center"><%= customer.try(:reify) ? customer.reify.country : customer.country %></td>
      <td class="align-middle text-center"><%= customer.try(:reify) ? customer.event : ' ' %></td>
      <td class="align-middle text-center"><%= customer.try(:reify) ? customer.created_at.strftime('%d/%m/%y') : ' ' %></td>
      <% if params[:action] == "index" %>
          <td ><%= link_to customer_path(customer) do %>
            <i class="fa-solid fa-eye"></i>
          <% end %> </td>
          <td ><%= link_to edit_customer_path(customer) do %>
            <i class="fa-solid fa-pencil"></i>
          <% end %> </td>
          <td ><%= link_to customer_path(customer), method: :delete, data: { confirm: 'Are you sure?' } do %>
            <i class="fa-solid fa-trash-can"></i>
          <% end %> </td>
          <td ><%= link_to 'Versions', versions_customer_path(customer), class: "text-decoration-none"%></td>
      <% end %>   
      <% if params[:action] == "versions" %>
        <td><%= link_to 'Preview This Version', version_customer_path(@customer, customer), class: "text-decoration-none" %></td>
      <% end %>
      <% if params[:action] == "deleted" %>
        <td><%= link_to 'Restore This Customer', restore_customer_path(customer), method: :post, class: "text-decoration-none" %></td>
      <% end %>
    </tr>
<% end %>

app/views/customers/_form.html.erb
<%= form_with(model: customer) do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
        <% customer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mt-2">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field mt-2">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field mt-2">
    <%= form.label :birthday %>
    <%= form.date_select :birthday, start_year: 1900, end_year: Time.now.year %>
  </div>

  <div class="field mt-2">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <%= form.submit class: 'btn btn-primary mt-3' %>
<% end %>

app/views/customers/deleted.html.erb
<div class="container mt-5">

  <% if notice %>
    <p id="notice">
      <div class="alert alert-success" role="alert">
        <%= notice %>
      </div>
    </p>
  <% end %>

  <h1 class="text-center m-5">Deleted Customers</h1>

  <%= link_to customers_path, class: "text-decoration-none" do %>
    <i class="fas fa-angle-double-left"></i> Back
  <% end %>

  <table class="table mt-4">
    <thead class='table-active th-text-color'>
      <tr>
        <th class="align-middle text-center">First name</th>
        <th class="align-middle text-center">Last name</th>
        <th class="align-middle text-center">Birthday</th>
        <th class="align-middle text-center">Country</th>
        <th colspan="7"></th>
      </tr>
    </thead>

    <tbody>
      <%= render partial: "customer", collection: @customers %>
    </tbody>
  </table>

  <br>
</div>

app/views/customers/edit.html.erb
<div class="container mt-5">

  <%= link_to customers_path, class: "text-decoration-none" do %>
    <i class="fas fa-angle-double-left"></i> Back
  <% end %>

  <h3 class="text-muted text-center mt-5">Editing Customer</h3>

  <div class="row mt-2">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="text-dark p-3 shadow">
        <%= render 'form', customer: @customer %>

        <div class="d-flex justify-content-end pe-5 edit-icon">
          <td ><%= link_to customer_path(@customer) do %>
            <i class="fa-solid fa-eye"></i>
          <% end %> </td>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/customers/index.html.erb
<div class="container mt-5">
  <% if notice %>
    <p id="notice">
      <div class="alert alert-danger" role="alert">
        <%= notice %>
      </div>
    </p>
  <% end %>

  <h1 class="text-center m-5">Customers</h1>

  <table class="table mt-3">
    <thead class='table-active th-text-color'>
      <tr>
        <th class="align-middle text-center">First name</th>
        <th class="align-middle text-center">Last name</th>
        <th class="align-middle text-center">Birthday</th>
        <th class="align-middle text-center">Country</th>
        <th colspan="7"></th>
      </tr>
    </thead>

    <tbody>
      <%= render @customers %>
    </tbody>
  </table>

  <br>

  <div class="d-flex">
    <div class="pe-3">
      <%= link_to 'New Customer', new_customer_path, class: 'btn btn-primary' %>
    </div>

    <div class="mb-5">
      <%= link_to "All Customers deleted", deleted_customers_path, class: 'btn btn-secondary' %>
    </div>
  </div>
</div>

app/views/customers/new.html.erb
<div class="container mt-5">

  <%= link_to customers_path, class: "text-decoration-none" do %>
    <i class="fas fa-angle-double-left"></i> Back
  <% end %>

  <h3 class="text-muted text-center mt-5">New Customer</h3>

  <div class="row mt-2">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="text-dark p-3 shadow">
        <%= render 'form', customer: @customer %>
      </div>
    </div>
  </div>

</div>

app/views/customers/show.html.erb
<div class="container mt-5">
  <% if notice %>
    <p id="notice">
      <div class="alert alert-success" role="alert">
        <%= notice %>
      </div>
    </p>
  <% end %>

  <%= link_to customers_path, class: "text-decoration-none" do %>
    <i class="fas fa-angle-double-left"></i> Back
  <% end %>

  <div class="row mt-5">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="text-dark p-3 shadow">
        <h3 class="text-muted text-center mb-2">Customer:</h3>
        <p>
          <strong>First name:</strong>
          <%= @customer.first_name %>
        </p>

        <p>
          <strong>Last name:</strong>
          <%= @customer.last_name %>
        </p>

        <p>
          <strong>Birthday:</strong>
          <%= @customer.birthday %>
        </p>

        <p>
          <strong>Country:</strong>
          <%= @customer.country %>
        </p>

        <div class="d-flex justify-content-end pe-3">
          <%= link_to edit_customer_path(@customer), class: 'btn btn-success' do %>
            <i class="fa-solid fa-pencil"></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/customers/version.html.erb
<div class="container mt-5">
  <% if notice %>
    <p id="notice">
      <div class="alert alert-success" role="alert">
        <%= notice %>
      </div>
    </p>
  <% end %>

  <%= link_to versions_customer_path(@version.item_id), class: "text-decoration-none" do %>
    <i class="fas fa-angle-double-left"></i> Back
  <% end %>

  <div class="row mt-5">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="text-dark p-3 shadow">
      <h3 class="text-muted text-center mb-2">Customer:</h3>
        <p>
          <strong>First Name:</strong>
          <%= @version.reify.first_name %>
        </p>

        <p>
          <strong>Last Name:</strong>
          <%= @version.reify.last_name %>
        </p>

        <p>
          <strong>Birthday:</strong>
          <%= @version.reify.birthday %>
        </p>

        <p>
          <strong>Country:</strong>
          <%= @version.reify.country %>
        </p>

        <p>
          <strong>Event:</strong>
          <%= @version.event %>
        </p>

        <p>
          <strong>Date:</strong>
          <%= @version.created_at.strftime('%d/%m/%y') %>
        </p>

        <div class="d-flex justify-content-end pe-3">
          <%= link_to 'Revert to this version', revert_customer_path(@version.item_id, @version), method: :post, class: 'btn btn-success' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/customers/versions.html.erb
<div class="container mt-5">
  <% if notice %>
    <p id="notice">
      <div class="alert alert-success" role="alert">
        <%= notice %>
      </div>
    </p>
  <% end %>

  <h1 class="text-center m-5">Previous Versions</h1>

  <%= link_to customers_path, class: "text-decoration-none" do %>
    <i class="fas fa-angle-double-left"></i> Back
  <% end %>

  <table class="table mt-4">
    <thead class='table-active th-text-color'>
      <tr>
        <th class="align-middle text-center">First name</th>
        <th class="align-middle text-center">Last name</th>
        <th class="align-middle text-center">Birthday</th>
        <th class="align-middle text-center">Country</th>
        <th class="align-middle text-center">Event</th>
        <th class="align-middle text-center">Date</th>
        <th colspan="7"></th>
      </tr>
    </thead>

    <tbody>
    <%= render partial: "customer", collection: @customers %>
    </tbody>
  </table>

  <br>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SecondChallange</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/2375142c1c.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>